spring:
  application:
    name: minesweeper-exam-service
    
spring.datasource:
  url: jdbc:postgresql://localhost:5432/minesweeper_db
  username: liquibase
  password: 
  driverClassName: org.postgresql.Driver     